pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.0.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_VERBOSE: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    version: '$(dotnetSdkVersion)'
    packageType: 'sdk'
    version: '8.0.x'

- script: |
    dotnet --info
    find . -name "*.csproj"
    for proj in $(find . -name "*.csproj"); do
      echo "Inspecting $proj"
      dotnet list "$proj" package
    done
  displayName: 'Debug .NET environment'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    arguments: '--verbosity detailed'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack the project - $(buildConfiguration)'
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
 
- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    feedPublish: '$(System.TeamProject)/Tailspin.SpaceGame.Web.Models'
    allowPackageConflicts: true
  condition: succeeded()
